# Generated by Django 6.0.1 on 2026-02-08 03:39

import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_photo_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background_image',
            field=models.ImageField(upload_to=web.models.character.background_image_upload_to),
        ),
    ]
